#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
src=(ROOT/'research'/'loto6_hist_rebuild_2135.py').read_text(encoding='utf-8')
old="""dc5,dc4=direct_core(X,pairc);score=(stat-ss[500].mean())/(ss[500].std()+1e-9)+.20*(dc5-c5.mean())/(c5.std()+1e-9)+.15*(dc4-c4.mean())/(c4.std()+1e-9)\n order=np.argsort(score)[::-1];sel,sum_quota,layer_quota=choose_diverse(order,combs,meta,10)"""
new="""dc5,dc4=direct_core(X,pairc);score=(stat-ss[500].mean())/(ss[500].std()+1e-9)+.20*(dc5-c5.mean())/(c5.std()+1e-9)+.15*(dc4-c4.mean())/(c4.std()+1e-9)\n # Weak frequency layer. Existing structural filters/quotas and Committee remain primary.\n # Previous main numbers receive NO frequency bonus, so a hot previous number (e.g. 35) is not pushed again by this layer.\n prev_arr=set(map(int,draws[-1]))\n num_freq=np.zeros(44,float)\n digit_freq=np.zeros(10,float)\n digit_card=np.array([4,5,5,5,4,4,4,4,4,4],float)\n for ww in (20,50,100):\n  cnt=np.bincount(draws[-ww:].ravel(),minlength=44).astype(float)\n  zz=(cnt[1:44]-cnt[1:44].mean())/(cnt[1:44].std()+1e-9)\n  num_freq[1:44]+=zz/3.0\n  dc=np.zeros(10,float)\n  for d in range(10):dc[d]=sum(cnt[n] for n in range(1,44) if n%10==d)\n  expected=6.0*ww*digit_card/43.0\n  ratio=dc/expected\n  zr=(ratio-ratio.mean())/(ratio.std()+1e-9)\n  digit_freq+=zr/3.0\n # Disable exact-number frequency effect for previous main numbers.\n for n in prev_arr:num_freq[n]=0.0\n cand_num=np.zeros(len(X),float);cand_digit=np.zeros(len(X),float)\n for ii,row in enumerate(X):\n  vals=[int(x) for x in row if int(x) not in prev_arr]\n  if vals:\n   cand_num[ii]=np.mean([num_freq[x] for x in vals])\n   cand_digit[ii]=np.mean([digit_freq[x%10] for x in vals])\n zn=(cand_num-cand_num.mean())/(cand_num.std()+1e-9)\n zd=(cand_digit-cand_digit.mean())/(cand_digit.std()+1e-9)\n frequency_adjust=0.10*zn+0.05*zd\n # Small preference for zero previous-main overlap; does not override structural quotas.\n prev_overlap_pref=0.03*(po==0).astype(float)\n final_score=score+frequency_adjust+prev_overlap_pref\n order=np.argsort(final_score)[::-1];sel,sum_quota,layer_quota=choose_diverse(order,combs,meta,10)"""
if old not in src:
 raise SystemExit('target block not found')
src=src.replace(old,new)
src=src.replace("'committee_score':float(score[i]),'rebuild_rank':int(np.where(order==i)[0][0])+1", "'committee_score':float(score[i]),'number_frequency_score':float(cand_num[i]),'last_digit_frequency_score':float(cand_digit[i]),'frequency_adjust':float(frequency_adjust[i]),'final_score':float(final_score[i]),'rebuild_rank':int(np.where(order==i)[0][0])+1")
src=src.replace("'method':'Stat200/500/800 + Committee Top500 support -> Core22 + Satellite6 -> temporal band rebuild -> ABCD/sum quota diversified Committee rerank'", "'method':'Existing 2135 flow preserved; weak 20/50/100 exact-number + last-digit frequency layer added only after Committee, with no frequency bonus for previous main numbers'")
src=src.replace("'actual_layer_counts':dict(Counter(x['layer'] for x in tickets))", "'frequency_weights':{'exact_number':0.10,'last_digit':0.05,'zero_prev_overlap_preference':0.03},'previous_main_frequency_bonus_disabled':sorted(prev_arr),'actual_layer_counts':dict(Counter(x['layer'] for x in tickets))")
src=src.replace("loto6_hist_rebuild_2135.json", "loto6_hist_rebuild_2135_freqsoft.json")
exec(compile(src,'loto6_hist_rebuild_2135_freqsoft_runtime.py','exec'),{'__name__':'__main__','__file__':str(ROOT/'research'/'loto6_hist_rebuild_2135_freqsoft_runtime.py')})
