from pathlib import Path
p=Path('miniloto-river.html')
s=p.read_text(encoding='utf-8')
repls=[
("--rel-prev2:#bd7cff}","--rel-prev2:#bd7cff;--rel-prev35:#f2c14e;--rel-outside:#9aa5b5}"),
('.relationChip[data-rel="prev2Near"] .swatch{background:var(--rel-prev2)}', '.relationChip[data-rel="prev2Near"] .swatch{background:var(--rel-prev2)}.relationChip[data-rel="prev35Same"] .swatch{background:var(--rel-prev35)}.relationChip[data-rel="outside"] .swatch{background:var(--rel-outside)}'),
('.relationChip.active[data-rel="prev2Near"]{border-color:var(--rel-prev2);box-shadow:0 0 0 1px rgba(189,124,255,.25) inset}', '.relationChip.active[data-rel="prev2Near"]{border-color:var(--rel-prev2);box-shadow:0 0 0 1px rgba(189,124,255,.25) inset}.relationChip.active[data-rel="prev35Same"]{border-color:var(--rel-prev35);box-shadow:0 0 0 1px rgba(242,193,78,.25) inset}.relationChip.active[data-rel="outside"]{border-color:var(--rel-outside);box-shadow:0 0 0 1px rgba(154,165,181,.25) inset}'),
('.relationHalo.prev2Near{stroke:var(--rel-prev2);stroke-width:2.5}', '.relationHalo.prev2Near{stroke:var(--rel-prev2);stroke-width:2.5}.relationHalo.prev35Same{stroke:var(--rel-prev35);stroke-width:2.3}.relationHalo.outside{stroke:var(--rel-outside);stroke-width:2.2;stroke-dasharray:3 2}'),
('    <button class="chip relationChip" data-rel="prev2Near"><span class="swatch"></span>2回前 同じ・±1</button>\n  </div>', '    <button class="chip relationChip" data-rel="prev2Near"><span class="swatch"></span>2回前 同じ・±1</button>\n    <button class="chip relationChip" data-rel="prev35Same"><span class="swatch"></span>3〜5回前 同じ</button>\n    <button class="chip relationChip" data-rel="outside"><span class="swatch"></span>4条件外</button>\n  </div>'),
('  <div class="helper">ボタンは複数同時にONできます。条件が重なる数字は、複数色のリングで表示します。</div>', '  <div class="helper">ボタンは複数同時にONできます。条件が重なる数字は複数色リングで表示。「4条件外」は前回同じ・前回±1・2回前同じ/±1・3〜5回前同じのどれにも該当しない当選数字です。</div>'),
('const relationOn={prevSame:false,prevNear:false,prev2Near:false};', 'const relationOn={prevSame:false,prevNear:false,prev2Near:false,prev35Same:false,outside:false};'),
('  const prev2=idx>1?mains(DATA[idx-2]):[];\n  return {\n    prevSame:prev.includes(n),\n    prevNear:prev.some(x=>Math.abs(n-x)===1),\n    prev2Near:prev2.some(x=>Math.abs(n-x)<=1)\n  };', '  const prev2=idx>1?mains(DATA[idx-2]):[];\n  const prev35=[];for(let k=3;k<=5;k++)if(idx>=k)prev35.push(...mains(DATA[idx-k]));\n  const prevSame=prev.includes(n);\n  const prevNear=prev.some(x=>Math.abs(n-x)===1);\n  const prev2Near=prev2.some(x=>Math.abs(n-x)<=1);\n  const prev35Same=prev35.includes(n);\n  return {prevSame,prevNear,prev2Near,prev35Same,outside:!(prevSame||prevNear||prev2Near||prev35Same)};'),
('    if(relationOn.prev2Near&&rel.prev2Near)a.push(`<circle cx="${xx}" cy="${y}" r="14" class="relationHalo prev2Near"/>`);\n    if(relationOn.prevNear&&rel.prevNear)a.push(`<circle cx="${xx}" cy="${y}" r="11.5" class="relationHalo prevNear"/>`);\n    if(relationOn.prevSame&&rel.prevSame)a.push(`<circle cx="${xx}" cy="${y}" r="9.8" class="relationHalo prevSame"/>`);', '    if(relationOn.outside&&rel.outside)a.push(`<circle cx="${xx}" cy="${y}" r="17" class="relationHalo outside"/>`);\n    if(relationOn.prev35Same&&rel.prev35Same)a.push(`<circle cx="${xx}" cy="${y}" r="15.5" class="relationHalo prev35Same"/>`);\n    if(relationOn.prev2Near&&rel.prev2Near)a.push(`<circle cx="${xx}" cy="${y}" r="14" class="relationHalo prev2Near"/>`);\n    if(relationOn.prevNear&&rel.prevNear)a.push(`<circle cx="${xx}" cy="${y}" r="11.5" class="relationHalo prevNear"/>`);\n    if(relationOn.prevSame&&rel.prevSame)a.push(`<circle cx="${xx}" cy="${y}" r="9.8" class="relationHalo prevSame"/>`);')
]
for old,new in repls:
    if old not in s:
        raise SystemExit('pattern not found: '+old[:100])
    s=s.replace(old,new,1)
# Add a compact diagnostic KPI for currently shown historical wins.
old="  const avg=(rs.reduce((s,r)=>s+mains(r).reduce((x,y)=>x+y,0),0)/rs.length).toFixed(1);\n  $('kpis').innerHTML=`<div class=\"card\"><div class=\"label\">表示期間</div><div class=\"n\">${rs.length}回</div></div><div class=\"card\"><div class=\"label\">最多出現</div><div class=\"n\">${hot.map(pad).join('・')}</div></div><div class=\"card\"><div class=\"label\">最新回の前回再登場</div><div class=\"n\">${re}個</div></div><div class=\"card\"><div class=\"label\">期間内 連番あり</div><div class=\"n\">${cr}%</div></div>`;"
new="  const avg=(rs.reduce((s,r)=>s+mains(r).reduce((x,y)=>x+y,0),0)/rs.length).toFixed(1);\n  let totalWins=0,outsideWins=0,rescue35=0;rs.forEach(r=>mains(r).forEach(n=>{totalWins++;const m=relationMatches(r,n);if(m.outside)outsideWins++;if(m.prev35Same&&!m.prevSame&&!m.prevNear&&!m.prev2Near)rescue35++;}));\n  $('kpis').innerHTML=`<div class=\"card\"><div class=\"label\">表示期間</div><div class=\"n\">${rs.length}回</div></div><div class=\"card\"><div class=\"label\">3〜5回前同一で追加救済</div><div class=\"n\">${rescue35}個</div></div><div class=\"card\"><div class=\"label\">4条件外</div><div class=\"n\">${outsideWins}個</div><div class=\"label\">${(100*outsideWins/Math.max(1,totalWins)).toFixed(1)}%</div></div><div class=\"card\"><div class=\"label\">期間内 連番あり</div><div class=\"n\">${cr}%</div></div>`;"
if old not in s: raise SystemExit('KPI pattern not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('updated',p)
